import { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  tutorial: [{ type: "autogenerated", dirName: "tutorial" }],
  theory: [{ type: "autogenerated", dirName: "theory" }],
};

export default sidebars;
