/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorial: [{type: 'autogenerated', dirName: 'tutorial'}],
  theory: [{type: 'autogenerated', dirName: 'theory'}],
};

module.exports = sidebars;
